services:
    ptrio_message.firebase_client:
        class: 'App\Ptrio\MessageBundle\Client\FirebaseClient'
        arguments:
            - '%ptrio_message.firebase.api_url%'
            - '%ptrio_message.firebase.server_key%'

    ptrio_message.device_voter:
        class: 'App\Ptrio\MessageBundle\Security\Voter\DeviceVoter'
        arguments:
            - '@security.access.decision_manager'
        tags:
            - { name: security.voter }

    ptrio_message.send_message_command:
        class: 'App\Ptrio\MessageBundle\Command\SendMessageCommand'
        arguments:
            - '@ptrio_message.firebase_client'
            - '@ptrio_message.device_manager'
            - '@ptrio_message.message_manager'
        tags:
            - { name: 'console.command' }

    ptrio_message.device_manager:
        class: 'App\Ptrio\MessageBundle\Doctrine\DeviceManager'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%ptrio_message.model.device.class%'
            - '@ptrio_message.device_repository'

    ptrio_message.add_message_command:
        class: 'App\Ptrio\MessageBundle\Command\AddDeviceCommand'
        arguments:
            - '@ptrio_message.device_manager'
        tags:
            - { name: 'console.command' }

    ptrio_message.remove_message_command:
        class: 'App\Ptrio\MessageBundle\Command\RemoveDeviceCommand'
        arguments:
            - '@ptrio_message.device_manager'
        tags:
            - { name: 'console.command' }

    ptrio_message.message_manager:
        class: 'App\Ptrio\MessageBundle\Doctrine\MessageManager'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%ptrio_message.model.message.class%'

    ptrio_message.list_device_messages_command:
        class: 'App\Ptrio\MessageBundle\Command\ListDeviceMessagesCommand'
        arguments:
            - '@ptrio_message.message_manager'
            - '@ptrio_message.device_manager'
        tags:
            - { name: 'console.command' }

    ptrio_message.device_repository:
        class: 'App\Ptrio\MessageBundle\Repository\DeviceRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%ptrio_message.model.device.class%'

    ptrio_message.device_type:
        class: 'App\Ptrio\MessageBundle\Form\Type\DeviceType'
        arguments:
            - '%ptrio_message.model.device.class%'
        tags:
            - { name: form.type, alias: 'ptrio_message_device_type' }

    ptrio_message.device_controller:
        class: 'App\Ptrio\MessageBundle\Controller\DeviceController'
        arguments:
            - '@ptrio_message.device_manager'
            - '@form.factory'
        tags:
            - { name: controller.service_arguments }

    ptrio_message.user_manager:
        class: 'App\Ptrio\MessageBundle\Doctrine\UserManager'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%ptrio_message.model.user.class%'

    ptrio_message.user_provider.api_key:
        class: 'App\Ptrio\MessageBundle\Security\Core\User\ApiKeyUserProvider'
        arguments:
            - '@ptrio_message.user_manager'

    ptrio_message.util.token_generator:
        class: 'App\Ptrio\MessageBundle\Util\TokenGenerator'

    ptrio_message.add_user_command:
        class: 'App\Ptrio\MessageBundle\Command\AddUserCommand'
        arguments:
            - '@ptrio_message.user_manager'
            - '@ptrio_message.util.token_generator'
        tags:
            - { name: console.command }

    ptrio_message.remove_user_command:
        class: 'App\Ptrio\MessageBundle\Command\RemoveUserCommand'
        arguments:
            - '@ptrio_message.user_manager'
        tags:
            - { name: console.command }

    ptrio_message.add_device_command:
        class: 'App\Ptrio\MessageBundle\Command\AddDeviceCommand'
        arguments:
            - '@ptrio_message.device_manager'
            - '@ptrio_message.user_manager'
        tags:
            - { name: console.command }

    ptrio_message.add_role_command:
        class: 'App\Ptrio\MessageBundle\Command\AddRoleCommand'
        arguments:
            - '@ptrio_message.user_manager'
        tags:
            - { name: console.command }

    ptrio_message.remove_role_command:
        class: 'App\Ptrio\MessageBundle\Command\RemoveRoleCommand'
        arguments:
            - '@ptrio_message.user_manager'
        tags:
            - { name: console.command }